apiVersion: v1
kind: Service
metadata:
    name: app3-flask
    labels:
        app: app3
spec:
    ports:
        - name: http
          port: 80
          targetPort: 5000
    selector:
        app: app3
    type: NodePort