apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app1
  name: app1
  namespace: webapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: tnogueir4/labhome:app1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
