apiVersion: v1
kind: Service
metadata:
    name: app1-flask
    labels:
        app: app1
spec:
    ports:
        - name: http
          port: 80
          targetPort: 5000
    selector:
        app: app1
    type: NodePort