apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app2
  name: app2
  namespace: webapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: tnogueir4/labhome:app2
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
