apiVersion: v1
kind: Service
metadata:
    name: app2-flask
    labels:
        app: app2
spec:
    ports:
        - name: http
          port: 80
          targetPort: 5000
    selector:
        app: app2
    type: NodePort